# Generated by Django 2.2 on 2020-05-02 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0002_userinfo_bol_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_zip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
