# Generated by Django 2.2 on 2020-05-03 09:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0005_userinfo_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
