# Generated by Django 2.2 on 2020-05-08 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0007_auto_20200503_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='bol_field',
            field=models.BooleanField(default=False),
        ),
    ]
