# Generated by Django 2.2 on 2020-05-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0008_userinfo_bol_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='bol_field',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
